# Generated by Django 2.2.16 on 2021-02-05 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_doctor_patient_workinghour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='WorkingHour',
        ),
    ]
