# Generated by Django 3.1.6 on 2021-02-05 13:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210205_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('nhs_num', models.IntegerField(primary_key=int, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(999999999), django.core.validators.MaxValueValidator(9999999999)])),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('nhs_num', models.IntegerField(primary_key=int, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('passworsd', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(999999999), django.core.validators.MaxValueValidator(9999999999)])),
                ('notes', models.CharField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('quantity', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notes', models.CharField(max_length=9999)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
    ]
