# Generated by Django 3.1.6 on 2021-02-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_booking_doctor_patient_workinghour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=int, serialize=False),
        ),
    ]
