# Generated by Django 3.1.6 on 2021-02-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210205_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghour',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=int, serialize=False),
        ),
    ]
